name: Docker Build and Push to GHCR and DockerHub

on:
  push:
    branches:
      - beta
  pull_request:
    branches: [ "beta" ]

env:
  # github container registry related
  GHCR_REGISTRY: ghcr.io
  GHCR_IMAGE_NAME: infuzio-backend
  G_HUB_TOKEN: ${{ secrets.GHUB_TOKEN }}
  

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # Log in to GitHub Container Registry (GHCR)
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.GHCR_REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.G_HUB_TOKEN }}

    # Extract metadata for GHCR
    - name: Extract metadata for GHCR
      id: meta_ghcr
      uses: docker/metadata-action@v3
      with:
        images: ${{ env.GHCR_REGISTRY }}/${{ env.GHCR_IMAGE_NAME }}

    # Build and push Docker image to GHCR
    - name: Build and push Docker image to GHCR
      uses: docker/build-push-action@v2
      id: docker_build_ghcr
      with:
        context: .
        push: true
        tags: |
          ${{ steps.meta_ghcr.outputs.tags }}
          ${{ env.GHCR_REGISTRY }}/${{ env.GHCR_IMAGE_NAME }}:latest
        labels: ${{ steps.meta_ghcr.outputs.labels }}
    #   continue-on-error: true  # Continue even if this step fails

    # - name: Image digest (GHCR)
    #   if: always()  # This step will always run
    #   run: |
    #     echo "GHCR digest: ${{ steps.docker_build_ghcr.outputs.digest }}"
    
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
